[package]
name = "usagestatsd"
version = "0.1.0"
authors = ["Danil Korennykh <bluskript@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = "0.2.22"
libc = "0.2"
procfs = "0.8.1"